### ISSUE TITLE
ENOENT Error using Windows 10

### ISSUE THREAD

**Issue by giovanihoff** [igniteram/appium-webdriverio-typescript#4]
According README.md and using SO Windows 10, during "**npm run app-test**", I have the following problem :

> appium-webdriverio-tests@1.0.0 app-test C:\dev\workspace\hoff\ticket\appium-webdriverio-typescript
> wdio ./config/wdio.app.config.js
> <<< NATIVE APP TESTS STARTED >>>
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn appium ENOENT
>     at _errnoException (util.js:992:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
>     at Function.Module.runMain (module.js:695:11)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! appium-webdriverio-tests@1.0.0 app-test: `wdio ./config/wdio.app.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the appium-webdriverio-tests@1.0.0 app-test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by viniciusxyz** [comment]
The same problem here

**Comment by igniteram** [comment]
@viniciusxyz @giovanihoff In windows there is a slight variation - 

You would have to replace the appium command in wdio.app.config.js to 'appium.cmd'  -
```
appium: {
        waitStartTime: 6000,
        waitforTimeout: waitforTimeout,
        command: 'appium.cmd',      <------- right here
        logFileName: 'appium.log',
        args: {
            address: host,
            port: port,
            commandTimeout: commandTimeout,
            sessionOverride: true,
            debugLogSpacing: true
        }
    }
```
The wdio-appium-service module was mainly developed using mac/linux systems that is why this windows related issue was not handled. There is already an issue open in their repo - https://github.com/rhysd/wdio-appium-service/issues/2

**Comment by giovanihoff** [comment]
Adjusted in Windows. Thank you @igniteram! @viniciusxyz, please, let us know it has been fixed to close this issue.

**Comment by eugengaspar** [comment]
Hi! 
Would there be any new updates regarding this package?
I would like to use under a WIN_10 OS :)
10Q!

**Comment by igniteram** [comment]
@eugengaspar Yes there would be updates, in fact plan is upgrade to new `WebdriverIO` which has whole lot of breaking changes which have to be investigated and configured with this framework.

Stay tuned for updates as this is an open source project, would only be able to spend my free time on it.
Currently occupied with work commitments. 🙄 

If you would like to contribute to this project , I would be more than happy to review and merge your PR. Give it a try if you get some time , please feel free to post questions 👍
